### ISSUE TITLE
WebGL Build not playing animations

### ISSUE THREAD

**Issue by monkydream** [keijiro/MidiAnimationTrack#10]
Tested with the included project and a new one on Unity 2019.4.13f1 and 2021.1.04b. The problem only appears with a WebGL build: sound is OK but no animations are playing. 

The console gives several warnings and errors (the FMOD one being probably unrelated and an [old bug](https://answers.unity.com/questions/1490213/fmod-returns-error-code-78-fmod-err-unimplemented.html)): 

<img width="852" alt="midianimWebGLB" src="https://user-images.githubusercontent.com/18001735/108508096-950c6380-72bb-11eb-9309-759b91720fe1.png">

Best (and thanks for ALL your amazing work),

Laurent

**Comment by keijiro** [comment]
I realized that code stripping works too much on WebGL. I added `link.xml` to exclude some classes that are used in the timeline.  

https://github.com/keijiro/MidiAnimationTrack/commit/c6365868ab590a88d2f0be5a26cee892783af14e

Please read the documentation about managed code stripping for further details.

https://docs.unity3d.com/Manual/ManagedCodeStripping.html

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
