### ISSUE TITLE
パッケージのインストールが始まらない

### ISSUE THREAD

**Issue by erina8m** [keijiro/MidiAnimationTrack#12]
初めまして。初心者のため的外れな質問かもしれないのですが、お聞きしたいことがあり連絡させて頂きました。

READMEに書いてある手順を踏んでもパッケージのインストールが始まらないのですが、
もし考えられる問題点/解決法があれば教えて頂けないでしょうか。
環境はMacユーザー・Unity 2020.3.14f1(2020.3.15fでも試しましたが変わりませんでした。)で、
エディタはVisual StudioとAtomをそれぞれ複数回試しました。

お手数をおかけしてしまい申し訳ないのですが教えて頂けますと幸いです。

**Comment by keijiro** [comment]
`manifest.json` に追加する dependency エントリの末尾にカンマをつけ忘れることなどが多いようです。
