### ISSUE TITLE
Midi assets not recongnized in timeline Unity 2020.2.6f1

### ISSUE THREAD

**Issue by vfabien21** [keijiro/MidiAnimationTrack#14]
I have just installed MidiAnimationTrack.
The Klak.Timeline.Midi appears as a choice in the timeline window. It is possible to create a Midi Animation Track. 
A midi file has been imported (succesfully ? see attachment).
However, I can't link the Midi file to the Midi Animation Track, nor can I drag an drop it from assets
[Mozart.mid.meta.txt](https://github.com/keijiro/MidiAnimationTrack/files/8178479/Mozart.mid.meta.txt)
.

**Comment by keijiro** [comment]
Did you see this gif?

https://i.imgur.com/WVMaG6J.gif

**Comment by vfabien21** [comment]
Solved : I did not realise they I had to drag the sub assets and not the whole asset
