### ISSUE TITLE
Imported MIDI clips not full length

### ISSUE THREAD

**Issue by antennatree** [keijiro/MidiAnimationTrack#2]
It seems that MIDI clips are not imported at their full length unless there is a note or CC event at the end of the clip.

For example if you have an 8 bar MIDI clip but the last bar only has a single note at the beginning of the bar it will import as a 7 bar MIDI clip. However, if you add a continuous CC modulation to the 8 bar clip it will properly import as 8 bars.

This doesn't really break anything, but it makes it a little more difficult to visually lay down clips on the Timeline when the last bar is missing (even if it technically has no information).

**Comment by antennatree** [comment]
I guess it does break the looping feature you implemented... if the bar is missing at the end then you can't just drag out another loop. You have to manually copy/paste the loops. And since they're too short they don't snap end to start.

**Comment by antennatree** [comment]
Just to clarify, the last bar needs to have information in it or it's not imported. I was saying the last bar wasn't importing even if there was a note at the beginning when I meant the second to last bar. Sorry about that.

**Comment by keijiro** [comment]
> Just to clarify, the last bar needs to have information in it or it's not imported.

Although your understanding is almost right, the importer can handle it correctly if the DAW puts the end-of-track meta event exactly at the end of the loop. As far as I tried, BitWig doesn't, and Ableton does. I'll re-check it later.

**Comment by keijiro** [comment]
I was wrong. Even Abeton doesn't put the end-of-track event correctly. I guess that most of DAWs nowadays can't handle it in a correct way. It's a bit pain, but please put a placeholder event in the last bar.

**Comment by antennatree** [comment]
Yeah, I was thinking it might be a problem on the exporter side. Easy
enough workaround to just put a token CC event at the end of any clip to
fix the length.

Thanks for the response.
