### ISSUE TITLE
animating property

### ISSUE THREAD

**Issue by michelezaccagnini** [keijiro/MidiAnimationTrack#22]
I am trying to have the Midi Animation Track animate a custom property. I create a property `ExampleProperty` (with a single integer value to `get` and `set`) in a script, then another script `MidiCtrl` with a `public ExampleProperty myval`. I add the `MidiCtrl` script to my object. The Midi Animation Track does not show the integer to as input. How do I expose the property values to the track?

![image](https://user-images.githubusercontent.com/11492957/190675030-db0b598e-188c-4877-a3f0-0b5ecd79450d.png)

**Comment by keijiro** [comment]
Could you try this?

https://github.com/keijiro/MidiAnimationTrack/issues/13#issuecomment-905068039

**Comment by keijiro** [comment]
I'm closing this issue as "answered". Please reopen it if it still reproduces.
