### ISSUE TITLE
Access CC data from script

### ISSUE THREAD

**Issue by michelezaccagnini** [keijiro/MidiAnimationTrack#23]
Hello!
I am trying to access a CC stream of data from a script. I got the Pitch and Velocity data correctly being reported with this function
```        
public void OnNotify
            (Playable origin, INotification notification, object context)
        {
            var signal = (MidiSignal)notification;
            float pitch    = signal.Event.data1;
            float velocity = signal.Event.data2;
        }
```
In the signal.Event I don't see any way to access the CC though. Is there an example I can look at to grab the CC from the Midi animation track?
Thanks!

**Comment by keijiro** [comment]
If I remember it correctly (I have 700+ projects on GitHub, so I can't remember the details about every project), as noted on README, the signal handler only detects key-on/off events. You have to use track controls to use CCs.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.
