### ISSUE TITLE
How to install the package

### ISSUE THREAD

**Issue by papitosan** [keijiro/MidiAnimationTrack#3]
Excuse me but I'm beginner and don't a lot about coding.
It seems that MidiAnimationTrack is exactly what I am looking for (trigger event in Unity with a midi file)
But I don't know how to use it. How can I install this in Unity?

Thanks.

**Comment by papitosan** [comment]
Thanks! I did that but after, how do you import the thing in Unity?

**Comment by papitosan** [comment]
Sorry to be dumb but I still not succeed.
From windows> Package Manager > Add package from Disk, I Browse to the modified manifest.json file. But nothing happen, cannot find midi Animator in the package list..

Also I 'm thinking to make a mobile game (ios and android)
Will it be compatible?

EDIT: I dragged all the package inside the asset folder in the project and now I can play the TEST project. Is that what It was supposed to be done?
 The program looks awesome from what I can see!

 Is it possible to activate and deactivate a gameObject with the Midi Signal Reciever?
Where to put the midi file to read? I created a game object, dragged it into this script and choose "GameObject.SetActive" on the menu but nothing happen

Thanks for your help

**Comment by keijiro** [comment]
You can't use the package manager UI to import this package.

Edit the manifest file (manifest.json) as written in README, then Unity Editor automatically detect it and start the importing process. You don't have to do anything from UI.

I'd like to discuss only the installation process in this issue ticket. Please create another issue ticket for other topics.
