### ISSUE TITLE
Activate or trigger Game object with midi file and Midi signal reciever

### ISSUE THREAD

**Issue by papitosan** [keijiro/MidiAnimationTrack#5]
So I dragged all the package inside the asset folder in the project and now I can play the TEST project. Is that what It was supposed to be done?

Is it possible to activate and deactivate a gameObject with the Midi Signal Reciever?
Where to put the midi file to read? I created a game object, dragged it into this script and choose "GameObject.SetActive" on the menu but nothing happen

Thanks for your help

**Comment by keijiro** [comment]
> Is it possible to activate and deactivate a gameObject with the Midi Signal Reciever?

Possible by invoking `GameObject.SetActive` in an event of the MIDI Signal Receiver.

**Comment by papitosan** [comment]
**"Possible by invoking GameObject.SetActive in an event of the MIDI Signal Receiver."**
it is the menu GameObject> SetActive(Bool) right?
because nothing happen,.

**"A MIDI animation track also supports sending Timeline Signals "**

Is it automatic or should I do something to send the note on message?

**"Set the receiver game object as the output destination of the track."**

How can I do that?

**Comment by keijiro** [comment]
I'd recommend learning how to use Timeline Signals first.
