### ISSUE TITLE
Properties doesn't appear in Control Element

### ISSUE THREAD

**Issue by fredazarty** [keijiro/MidiAnimationTrack#7]
Hi Keijiro,

First, thank you for this package! It's really helpful! 

I have some issues to define a property in a  MonoBehaviour.

The documentation mention : 

**_Please note that it requires a public property to be animated; Just providing a public variable is not enough._**

So I followed the ["Creating Properties"](https://learn.unity.com/tutorial/creating-properties)  tutorial of unity to create something like : 

```
public class TestProp : MonoBehaviour
{
    private float experience;

    //Experience is a basic property
    public float Experience
    {
        get
        {
            //Some other code
            return experience;
        }
        set
        {
            //Some other code
            experience = value;
        }
    }   
}
```

But the property doesn't appear  in the Control Element 

![Screenshot 2020-10-02 at 22 31 35](https://user-images.githubusercontent.com/59411284/94967285-0e6b0b80-04ff-11eb-8f3d-7474e78e9877.png)

What did I miss ?

**Comment by keijiro** [comment]
Could you try renaming as follows?

```
private float m_experience;

//Experience is a basic property
public float experience
```

**Comment by fredazarty** [comment]
Thank you for your fast answer!

I have the same result with your modification : 

```
public class TestProp : MonoBehaviour
{
    private float m_experience;

    public float experience
    {
        get
        {
            return m_experience;
        }
        set
        {
            m_experience = value;
        }
    }    
}
```

**Comment by keijiro** [comment]
Try adding the SerializeField attribute to `m_experience`.

```
[SerializeField] private float m_experience;
```

**Comment by fredazarty** [comment]
It's work! Thank you 👍 !
I put the final code for others who will have the need :) 

```
public class TestProp : MonoBehaviour
{

    [SerializeField] 
    private float m_experience;

    public float experience
    {
        get
        {
            //Some other code
            return m_experience;
        }
        set
        {
            //Some other code
            m_experience = value;
        }
    }
    
}
```
